server:
  port: 8001

greeting:
  morning:
    en: "Good morning, {name}!"
    es: "¡Buenos días, {name}!"
  afternoon:
    en: "Good afternoon, {name}!"
    es: "¡Buenas tardes, {name}!"
  evening:
    en: "Good evening, {name}!"
    es: "¡Buenas noches, {name}!"
